# Generated by Django 4.1 on 2022-09-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtor_id',
            new_name='realtor',
        ),
    ]
