# Generated by Django 4.1 on 2022-09-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_city_alter_listing_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
